CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE COLLATION case_insensitive (LOCALE = 'en-u-ks-primary',
        PROVIDER = icu,
        DETERMINISTIC = False
    );
    CREATE TYPE schedule AS ENUM ('none', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday');
    CREATE TYPE tag_type AS ENUM ('carnivore', 'vegetarian', 'vegan', 'breakfast', 'lunch', 'dinner', 'supper');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "Tag" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Type" tag_type NOT NULL,
        CONSTRAINT "PK_Tag" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" integer NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" integer NOT NULL,
        "RoleId" integer NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" integer NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "ManageableEntity" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Title" character varying(20) COLLATE case_insensitive NOT NULL,
        "ApplicationUserId" integer NOT NULL,
        CONSTRAINT "PK_ManageableEntity" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ManageableEntity_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "ShoppingItem" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(20) NOT NULL,
        "Measurement" character varying(20),
        "Price" numeric(12,2),
        "Quantity" integer,
        "IsChecked" boolean NOT NULL,
        "IsLocked" boolean NOT NULL,
        "IsGenerated" boolean NOT NULL,
        "ApplicationUserId" integer NOT NULL,
        CONSTRAINT "PK_ShoppingItem" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ShoppingItem_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "Image" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "StorageFileName" character varying(12) NOT NULL,
        "DisplayFileName" character varying(255) NOT NULL,
        "ImagePath" character varying(255) NOT NULL,
        "ImageUrl" character varying(255) NOT NULL,
        "ManageableEntityId" integer NOT NULL,
        CONSTRAINT "PK_Image" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Image_ManageableEntity_ManageableEntityId" FOREIGN KEY ("ManageableEntityId") REFERENCES "ManageableEntity" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "Meal" (
        "Id" integer NOT NULL,
        "Schedule" schedule NOT NULL,
        CONSTRAINT "PK_Meal" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Meal_ManageableEntity_Id" FOREIGN KEY ("Id") REFERENCES "ManageableEntity" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "Recipe" (
        "Id" integer NOT NULL,
        "Description" character varying(255),
        "RecipeDetails_PrepTime" integer,
        "RecipeDetails_CookTime" integer,
        "RecipeDetails_Servings" integer,
        "RecipeNutrition_Calories" integer,
        "RecipeNutrition_Fat" integer,
        "RecipeNutrition_Carbs" integer,
        "RecipeNutrition_Protein" integer,
        CONSTRAINT "PK_Recipe" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Recipe_ManageableEntity_Id" FOREIGN KEY ("Id") REFERENCES "ManageableEntity" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "MealTag" (
        "MealsId" integer NOT NULL,
        "TagsId" integer NOT NULL,
        CONSTRAINT "PK_MealTag" PRIMARY KEY ("MealsId", "TagsId"),
        CONSTRAINT "FK_MealTag_Meal_MealsId" FOREIGN KEY ("MealsId") REFERENCES "Meal" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MealTag_Tag_TagsId" FOREIGN KEY ("TagsId") REFERENCES "Tag" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "Direction" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RecipeId" integer NOT NULL,
        "Number" integer NOT NULL,
        "Description" character varying(255) NOT NULL,
        CONSTRAINT "PK_Direction" PRIMARY KEY ("RecipeId", "Id"),
        CONSTRAINT "FK_Direction_Recipe_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES "Recipe" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "MealRecipe" (
        "MealId" integer NOT NULL,
        "RecipeId" integer NOT NULL,
        CONSTRAINT "PK_MealRecipe" PRIMARY KEY ("MealId", "RecipeId"),
        CONSTRAINT "FK_MealRecipe_Meal_MealId" FOREIGN KEY ("MealId") REFERENCES "Meal" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MealRecipe_Recipe_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES "Recipe" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "SubIngredient" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RecipeId" integer NOT NULL,
        "Name" character varying(20) COLLATE case_insensitive,
        CONSTRAINT "PK_SubIngredient" PRIMARY KEY ("RecipeId", "Id"),
        CONSTRAINT "FK_SubIngredient_Recipe_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES "Recipe" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "Tip" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RecipeId" integer NOT NULL,
        "Description" character varying(255) NOT NULL,
        CONSTRAINT "PK_Tip" PRIMARY KEY ("RecipeId", "Id"),
        CONSTRAINT "FK_Tip_Recipe_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES "Recipe" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE TABLE "Ingredient" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "SubIngredientRecipeId" integer NOT NULL,
        "SubIngredientId" integer NOT NULL,
        "Name" character varying(20) NOT NULL,
        "Measurement" character varying(20) NOT NULL,
        CONSTRAINT "PK_Ingredient" PRIMARY KEY ("SubIngredientRecipeId", "SubIngredientId", "Id"),
        CONSTRAINT "FK_Ingredient_SubIngredient_SubIngredientRecipeId_SubIngredien~" FOREIGN KEY ("SubIngredientRecipeId", "SubIngredientId") REFERENCES "SubIngredient" ("RecipeId", "Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    INSERT INTO "Tag" ("Id", "Type")
    VALUES (1, 'carnivore'::tag_type);
    INSERT INTO "Tag" ("Id", "Type")
    VALUES (2, 'vegetarian'::tag_type);
    INSERT INTO "Tag" ("Id", "Type")
    VALUES (3, 'vegan'::tag_type);
    INSERT INTO "Tag" ("Id", "Type")
    VALUES (4, 'breakfast'::tag_type);
    INSERT INTO "Tag" ("Id", "Type")
    VALUES (5, 'lunch'::tag_type);
    INSERT INTO "Tag" ("Id", "Type")
    VALUES (6, 'dinner'::tag_type);
    INSERT INTO "Tag" ("Id", "Type")
    VALUES (7, 'supper'::tag_type);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Direction_RecipeId_Number" ON "Direction" ("RecipeId", "Number");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Image_ManageableEntityId" ON "Image" ("ManageableEntityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Image_StorageFileName" ON "Image" ("StorageFileName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ManageableEntity_ApplicationUserId_Title" ON "ManageableEntity" ("ApplicationUserId", "Title");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE INDEX "IX_MealRecipe_RecipeId" ON "MealRecipe" ("RecipeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE INDEX "IX_MealTag_TagsId" ON "MealTag" ("TagsId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE INDEX "IX_ShoppingItem_ApplicationUserId" ON "ShoppingItem" ("ApplicationUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_SubIngredient_RecipeId_Name" ON "SubIngredient" ("RecipeId", "Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Tag"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Tag") + 1,
            nextval(pg_get_serial_sequence('"Tag"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250517000121_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250517000121_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

