services:
  api:
    image: api
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile

  database:
    image: postgres:latest
    container_name: mealplannerdb
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - app_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  app_data: